version: "3"
services:
  web:
    build: .
    command: ./scripts/start.sh
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"