version: '3'
services:
  web:
    build: .
    command: ./scripts/start.sh
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: i_am_free_dev
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
